"""empty message

Revision ID: 0c7ae558ef08
Revises: 5c65b0011db0
Create Date: 2020-07-29 17:01:26.148276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c7ae558ef08'
down_revision = '5c65b0011db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_token', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('api_token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_api_token'), 'users', ['api_token'], unique=True)
    op.drop_index('ix_users_token', table_name='users')
    op.drop_column('users', 'token_expiration')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('token_expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_users_token', 'users', ['token'], unique=True)
    op.drop_index(op.f('ix_users_api_token'), table_name='users')
    op.drop_column('users', 'api_token_expiration')
    op.drop_column('users', 'api_token')
    # ### end Alembic commands ###
