"""Initial create

Revision ID: 866cac492c7e
Revises: 
Create Date: 2020-07-06 21:33:16.769206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866cac492c7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('fullname', sa.String(length=130), nullable=False),
    sa.Column('size', sa.String(length=120), nullable=False),
    sa.Column('path', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_fullname'), 'file', ['fullname'], unique=False)
    op.create_index(op.f('ix_file_name'), 'file', ['name'], unique=False)
    op.create_index(op.f('ix_file_user_id'), 'file', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_user_id'), table_name='file')
    op.drop_index(op.f('ix_file_name'), table_name='file')
    op.drop_index(op.f('ix_file_fullname'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
