"""New file table structure

Revision ID: a154e6cfe8ae
Revises: 7bbac43f1d0d
Create Date: 2020-07-04 21:44:03.869117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a154e6cfe8ae'
down_revision = '7bbac43f1d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('fullname', sa.String(length=130), nullable=True))
    op.add_column('file', sa.Column('name', sa.String(length=120), nullable=True))
    op.drop_column('file', 'filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('filename', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120), nullable=True))
    op.drop_column('file', 'name')
    op.drop_column('file', 'fullname')
    # ### end Alembic commands ###
